services:
  avl2gtfsrt-worker:
    environment:
      - PYTHONPATH=src
    command: "python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m avl2gtfsrt worker"
    ports:
      - "5678:5678"
  avl2gtfsrt-server:
    environment:
      - PYTHONPATH=src
    command: "python -m debugpy --listen 0.0.0.0:5679 --wait-for-client -m avl2gtfsrt server"
    ports:
      - "5679:5679"

  avl2gtfsrt-publisher:
    environment:
      - PYTHONPATH=src
    command: "python -m debugpy --listen 0.0.0.0:5680 --wait-for-client -m avl2gtfsrt publisher"
    ports:
      - "5680:5680"