services:
  avl2gtfsrt-mongodb:
    image: mongo:latest
    restart: unless-stopped
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${A2G_MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${A2G_MONGODB_PASSWORD}
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
  avl2gtfsrt-worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    command: "python -m avl2gtfsrt worker"
    environment:
      - A2G_DEBUG
      - A2G_ORGANISATION_ID
      - A2G_ITCS_ID
      - A2G_MONGODB_USERNAME
      - A2G_MONGODB_PASSWORD
      - A2G_WORKER_MQTT_HOST
      - A2G_WORKER_MQTT_PORT
      - A2G_WORKER_MQTT_USERNAME
      - A2G_WORKER_MQTT_PASSWORD
      - A2G_WORKER_MQTT_CLIENT_SUFFIX
      - A2G_NOMINAL_ADAPTER_TYPE
      - A2G_NOMINAL_ADAPTER_CONFIG
      - A2G_NOMINAL_CACHING_ENABLED
      - A2G_MATCHING_DATA_REVIEW_SECONDS
      - A2G_MATCHING_MAX_DATA_POINTS
      - A2G_MATCHING_MAX_INTERVAL
      - A2G_MATCHING_MAX_FAILURES
    depends_on:
      "avl2gtfsrt-mongodb":
        condition: service_healthy
  avl2gtfsrt-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    command: "python -m avl2gtfsrt server"
    ports:
      - "${A2G_SERVER_PORT:-9000}:9000"
    environment:
      - A2G_DEBUG
      - A2G_MONGODB_USERNAME
      - A2G_MONGODB_PASSWORD
      - A2G_SERVER_TIMEZONE
    depends_on:
      "avl2gtfsrt-mongodb":
        condition: service_healthy